name: .NET Core Desktop

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: pak-loader.sln
      WindowsSDKVersion: 10.0.19041.0

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0


    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Build Artifacts
        path: x64/${{ env.Configuration }}/*.dll
